server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
project:
  nema: hana-package
spring:
  profiles:
    active: local
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
jwt:
  secret: hn-package
  validity: 50000
