spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
      username: sa
  flyway:
    locations: classpath:db/data/common, classpath:db/data/test
  jpa:
    show-sql: true
