server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
project:
  nema: hana-package
spring:
  profiles:
    active: local
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
jwt:
  secret: hn-package
  validity: 50000

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_ID}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: hana-package.syopingbaeg.com
    region:
      static: ap-northeast-2
    stack:
      auto: false

ncloud:
  access-key: AHL1xW1z45NwpMjGoG43
  secret-key: 4zob2sBjJwPVqjbkXIIzTHK2cx4tIiuny7R88DCi
  email:
    address: 'zero2080@naver.com'
    url: https://mail.apigw.ntruss.com
    path: /api/v1/mails

info:
  app:
    profile: ${spring.profiles.active}
  environment:
    os: ${os.name}
    timezone: ${user.timezone}