spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 20
      maximum-pool-size: 50
      jdbc-url: jdbc:mysql://server-db.c9vq7tfs4ivu.ap-northeast-2.rds.amazonaws.com:3306/peachy?characterEncoding=UTF-8&useSSL=false
      username: hn-package
      password: hn-package!
  flyway:
    locations: classpath:db/data/common
