project:
  nema: project
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/project
    username: sa
    password: